### ISSUE TITLE
Not logging in 

### ISSUE THREAD

**Issue by sasukan** [nicoco007/LoL-Auto-Login#15]
So I am using 2.0.2 version and all that happen is league opens up to the login and nothing happens. 

[2017-04-08T18-04-31_LoLAutoLogin.txt](https://github.com/nicoco007/LoL-Auto-Login/files/907918/2017-04-08T18-04-31_LoLAutoLogin.txt)

**Comment by nicoco007** [comment]
Looks like the program is grabbing on to the wrong window. I'll see what I can do.

**Comment by s-k-y-l-i** [comment]
I have this problem too :/

**Comment by nicoco007** [comment]
If you are still around, this issue is similar to #21 where I'm posting my progress. You can try out the builds I've been posting there and see if they work; if not, feel free to post your updates in that issue.
