### ISSUE TITLE
LoL Update

### ISSUE THREAD

**Issue by nihaals** [nicoco007/LoL-Auto-Login#18]
If there's an update, it will show the notice, however, when it is restarted, autologin doesn't detect it. Is there a way to check on the screen if there's an update notice, and if there is, close it and rerun so it will still autologin after? Otherwise, you have to wait until after the update is done, then restart using autologin

**Comment by nicoco007** [comment]
It's definitely something I've been thinking about. It should be possible &ndash; I just have to figure out a way to force the client to continually show this notice so I can test it properly. I'm not sure if this will make it into version 2.1.0 or not; it depends on if I'm able to get reliable testing.

For now, you can re-run LoL Auto Login without closing the client and it should enter the password if you're on the login screen.

**Comment by nicoco007** [comment]
I've got an idea for something that should be able to detect these kinds of dialogs, so I'm aiming to implement this in version 2.2.0.

**Comment by nicoco007** [comment]
Should be good to go once version 2.3.0 is released! If the issue still arises, please feel free to reopen this issue or create a new one.
