### ISSUE TITLE
Changed Password

### ISSUE THREAD

**Issue by UnderwearDood** [nicoco007/LoL-Auto-Login#19]
I've had LoL-Auto-Login has worked ever since i downloaded it (about half a year) but now, for some reason the password has changed. It used to put in the right password, but know i just puts in one letter and presses enter. This started happening about 3-4 weeks ago. Thx for the help

**Comment by nicoco007** [comment]
I've been getting reports of similar issues. I think I've managed to isolate the problem. I'll get back to you very soon with a working version so you can test it.

**Comment by nicoco007** [comment]
If you are still around, this issue is similar to #21 where I'm posting my progress. You can try out the builds I've been posting there and see if they work; if not, feel free to post your updates in that issue.
