### ISSUE TITLE
Issues entering password

### ISSUE THREAD

**Issue by ghost** [nicoco007/LoL-Auto-Login#20]
In the log, it says successfully entered password:
0:00:00:00.0015038 [INFO] Started LoL Auto Login v2.0.2.0
0:00:00:00.0095247 [INFO] Loading settings from "D:\League of Legends\Config\LoLAutoLoginSettings.yaml"
0:00:00:00.0451198 [INFO] Loaded settings.
0:00:00:00.0892369 [INFO] Client is not running, launching client.
0:00:00:00.0922447 [INFO] Waiting for 30000 ms.
0:00:00:00.5982917 [INFO] Found new/resized window: {Handle=458870, Name="League of Legends", Class="RCLIENT", Rectangle={X=0,Y=0,Width=1024,Height=576}}
0:00:00:00.6012996 [INFO] Client found after 478 ms!
0:00:00:01.6336060 [INFO] Found new/resized window: {Handle=458870, Name="League of Legends", Class="RCLIENT", Rectangle={X=512,Y=268,Width=1024,Height=576}}
0:00:00:02.1474756 [INFO] Password box found after 2024 ms!
0:00:00:02.1570012 [INFO] Entering password...
0:00:00:02.1780568 [INFO] Successfully entered password (well, hopefully)!
0:00:00:02.1855771 [INFO] Pixel matching statistics:
0:00:00:02.1895873 [INFO]   Minimum: 0.06934 (71/1024)
0:00:00:02.1920941 [INFO]   Maximum: 0.82227 (842/1024)
0:00:00:02.1951015 [INFO]   Required: 0.80000 (819/1024)
0:00:00:02.1971071 [INFO] Shutting down

**Comment by nicoco007** [comment]
This seems to be a similar issue to #19. I'll close this issue and post any updates there.
