### ISSUE TITLE
Opening LoL but not entering password

### ISSUE THREAD

**Issue by clay10101** [nicoco007/LoL-Auto-Login#21]
Hi, new to github.

I've not been able to use lol-auto-login for maybe a fortnight or so, maybe more. I run at 4k with 150% scaling, if that might be causing an issue?

Latest log here:
**0:00:00:00.0035025 [INFO] Started LoL Auto Login v2.0.2.0
0:00:00:00.0195132 [INFO] Loading settings from "C:\Riot Games\League of Legends\Config\LoLAutoLoginSettings.yaml"
0:00:00:00.0930621 [INFO] Loaded settings.
0:00:00:00.1801203 [INFO] Found new/resized window: {Handle=722634, Name="League of Legends", Class="RCLIENT", Rectangle={X=413,Y=180,Width=1920,Height=1080}}
0:00:00:00.1811211 [INFO] Client is already open!
0:00:00:00.2326554 [INFO] Client doesn't seem to be on login page. Focusing client.
0:00:00:00.2421613 [INFO] Deleting 2 old log files...
0:00:00:00.2436626 [INFO] Done.
0:00:00:00.2461643 [INFO] Pixel matching statistics:
0:00:00:00.2466647 [INFO]   Minimum: 0.05273 (54/1024)
0:00:00:00.2471651 [INFO]   Maximum: 0.05273 (54/1024)
0:00:00:00.2471651 [INFO]   Required: 0.85000 (870/1024)
0:00:00:00.2476656 [INFO] Shutting down
**

**Comment by nicoco007** [comment]
That's most likely the issue. I honestly hadn't though of scaling when I first created this program; I'll add it to my testing process. This should be fixed in the next release. Thanks for the report!

**Comment by clay10101** [comment]
No worries! Glad I could help. Great little tool by the way. I've been
using it for ages! So dumb that LoL doesn't auto remember. I barely even
play it anymore, but I still keep an eye on Lol auto login.

Have a great day.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nicoco007** [comment]
Would you be able to send me screenshots of your client in the login screen (in all sizes listed in Settings > General if possible)? I don't have a 4K monitor on hand and it would help make recognition more accurate on high DPI screens.

**Comment by clay10101** [comment]
Not at home for a few days but I will do this Sunday/Monday for you.

**Comment by clay10101** [comment]
This is at 150% scaling on 4k.  Is that what you were looking for?
![1024x576](https://user-images.githubusercontent.com/39123533/40023912-7847243e-57c4-11e8-9309-62abe6c4728e.png)
![1280x720](https://user-images.githubusercontent.com/39123533/40023913-78632ca6-57c4-11e8-90f8-ae18d2a6f545.png)
![1600x900](https://user-images.githubusercontent.com/39123533/40023914-787d307e-57c4-11e8-8a47-cb1cf3139960.png)
![1920x1080](https://user-images.githubusercontent.com/39123533/40023916-7898aec6-57c4-11e8-96e2-0dabfb8a7a88.png)

**Comment by nicoco007** [comment]
That's exactly what I was looking for, thanks! I should be able to get a working version for you to try out very soon (most likely by the end of the week).

**Comment by nicoco007** [comment]
Hey! Sorry for taking so long. Could you try [this build](https://ci.gnyra.com/job/LoL-Auto-Login/job/master/51/artifact/LoLAutoLogin-master-51.zip) out? You'll have to manually put the files in your League of Legends folder. I recommend that you uninstall/remove the version you currently have and reinstall it after you're done testing.

**Comment by nicoco007** [comment]
I just noticed you might have to open Properties on the zip files and check the "Unblock" checkbox at the bottom. Windows doesn't seem to like the file for some reason.

**Comment by clay10101** [comment]
Hi, This build works for me! I noticed my Avast popped up a shield window on the first attempt. so I disabled the file shield and behaviour shield and the build worked. I included the latest log.

Could potentially be that a lot of people are experiencing problems due to Avast blocking the program.
(edit - have turned avast back on and lol auto login still works)
[2018-05-29T18-56-58_LoLAutoLogin.log](https://github.com/nicoco007/LoL-Auto-Login/files/2049850/2018-05-29T18-56-58_LoLAutoLogin.log)

Apologies for the delay. been real busy this last week starting a new job.

**Comment by NicolasGnyra-Accedo** [comment]
Hmmm. That's annoying. I'll try to check it out tonight.

**Comment by nicoco007** [comment]
Hmmm. That's annoying. I'll try to check it out tonight.

**Comment by ghost** [comment]
Has this been fixed yet? Im having the same issue here are my logs

> 0:00:00:00.0344944 [INFO] Started LoL Auto Login v2.0.2.0
> 0:00:00:00.1077547 [INFO] Loading settings from "C:\Riot Games\League of Legends\Config\LoLAutoLoginSettings.yaml"
> 0:00:00:00.1111819 [INFO] Settings file does not exist, using default settings.
> 0:00:00:00.4909272 [INFO] Password file not found, prompting user to enter password...
> 0:00:00:15.1811614 [INFO] Encrypting & saving password to file...
> 0:00:00:15.5275758 [INFO] Client is not running, launching client.
> 0:00:00:15.5280603 [INFO] Waiting for 30000 ms.
> 0:00:00:18.2786847 [INFO] Found new/resized window: {Handle=1114998, Name="League of Legends", Class="RCLIENT", Rectangle={X=0,Y=0,Width=1024,Height=576}}
> 0:00:00:18.3328287 [INFO] Client found after 2758 ms!
> 0:00:00:20.1604636 [INFO] Found new/resized window: {Handle=1114998, Name="League of Legends", Class="RCLIENT", Rectangle={X=128,Y=52,Width=1280,Height=720}}
> 0:00:00:32.3065284 [INFO] Client window lost!
>

**Comment by nicoco007** [comment]
Unfortunately I haven't had much time lately to do anything. You might have some luck with this [beta build](https://ci.gnyra.com/job/LoL-Auto-Login/job/master/54/artifact/LoLAutoLogin-master-54.zip) but I can't guarantee it'll work properly all the time (if at all). I'm trying to get something stable out soon, but I can't say for when just yet.

**Comment by ghost** [comment]
It didnt work installing the beta. So Ill guess i just have to wait.. can you at least give an ETA is it weeks, months or?

**Comment by nicoco007** [comment]
Hopefully in the coming couple of weeks, but I really can't promise anything.

**Comment by nicoco007** [comment]
Alright, I got something that should make more sense. @clay10101 and @mombo2811, could you both try this build out: [download the installer here](https://github.com/nicoco007/LoL-Auto-Login/files/2161611/LoLAutoLogin-v2.1.0.81-Installer.zip) or the [portable version here](https://github.com/nicoco007/LoL-Auto-Login/files/2161609/LoLAutoLogin-master-81.zip). You might want to completely uninstall any previous versions since I had to change the way the installer works.

**Comment by nicoco007** [comment]
Again, you might have to open Properties on the zip files and check the "Unblock" checkbox at the bottom. (I think it's a Windows Defender thing. It does strange things.)

**Comment by possessed1911** [comment]
You could make an installer and use this program to automatically unblock the file.
https://docs.microsoft.com/en-us/sysinternals/downloads/streams
Sry for hijacking the issue, but, can you add native support to use multiple accounts? I have added username into my own build, but I have to compile one file for each account ( I was lazy to look into something better);

**Comment by nicoco007** [comment]
The installer also suffers from this problem, so that's not really a possibility. Either way, when using the installer, the files it extracts aren't blocked. I don't think it's worth the effort since you essentially just need to check a box:

![properties](https://user-images.githubusercontent.com/1349975/42396793-356d1628-8131-11e8-8cf5-da8b323fb2d5.png)

As for multiple accounts, I've set up a basic roadmap of what needs to be done over at #13. You can put your suggestions/ideas/comments over there. I'll start working on it as soon as this issue has been properly dealt with.

**Comment by nicoco007** [comment]
Here's another build to try out if anyone's interested: https://ci.gnyra.com/blue/organizations/jenkins/LoL-Auto-Login/detail/develop/100/artifacts
