### ISSUE TITLE
Opening LoL but not entering password

### ISSUE THREAD

**Issue by Oussail** [nicoco007/LoL-Auto-Login#23]
Latest log : 
0:00:00:00.0019944 [INFO] Started LoL Auto Login v2.1.0.0
0:00:00:00.0079787 [INFO] OS Version: Microsoft Windows 10 Home release 1803 x64
0:00:00:00.0129652 [INFO] Screen \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
0:00:00:00.0189495 [INFO] Loading client info from "D:\Riot Games\League of Legends\Config\LeagueClientSettings.yaml"
0:00:00:00.1077114 [INFO] Region: EUW; Locale: en_GB
0:00:00:00.1156908 [INFO] Loading settings from "D:\Riot Games\League of Legends\Config\LoLAutoLoginSettings.yaml"
0:00:00:00.1226721 [INFO] Settings file does not exist, using default settings.
0:00:00:00.2084426 [INFO] Password file not found, prompting user to enter password
0:00:00:07.6493779 [INFO] Encrypting & saving password to file
0:00:00:07.6922656 [INFO] Client is not running, launching client
0:00:00:07.6982491 [INFO] Waiting for 30000 ms
0:00:00:09.3857338 [FATAL] Failed to run login sequence
0:00:00:09.3947099 [ERROR] An error of type System.TypeInitializationException occured: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
0:00:00:09.4046836 [ERROR]    at Emgu.CV.CvInvoke.cvCreateImageHeader(Size size, IplDepth depth, Int32 channels)
0:00:00:09.4046836 [ERROR]    at Emgu.CV.Image`2.AllocateData(Int32 rows, Int32 cols, Int32 numberOfChannels)
0:00:00:09.4046836 [ERROR]    at Emgu.CV.Image`2.set_Bitmap(Bitmap value)
0:00:00:09.4046836 [ERROR]    at Emgu.CV.Image`2..ctor(Bitmap bmp)
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.Util.CompareImage(Bitmap source, Dictionary`2 templates, Double tolerance, RectangleF areaOfInterest)
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.ClientControl.GetPasswordRect(Window clientWindow)
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.ClientControl.GetClientWindow()
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.ClientControl.AwaitClientHandle()
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.ClientControl.<>c.<RunLogin>b__3_0()
0:00:00:09.4046836 [ERROR]    at System.Threading.Tasks.Task.InnerInvoke()
0:00:00:09.4046836 [ERROR]    at System.Threading.Tasks.Task.Execute()
0:00:00:09.4046836 [ERROR] --- End of stack trace from previous location where exception was thrown ---
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.ClientControl.<RunLogin>d__3.MoveNext()
0:00:00:09.4046836 [ERROR] --- End of stack trace from previous location where exception was thrown ---
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
0:00:00:09.4046836 [ERROR]    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
0:00:00:09.4046836 [ERROR]    at LoLAutoLogin.MainForm.<saveButton_Click>d__5.MoveNext()
0:00:00:14.3371146 [INFO] Opening D:\Riot Games\League of Legends\Logs\LoL Auto Login Logs\2018-06-28T18-33-15_LoLAutoLogin.log

**Comment by nicoco007** [comment]
Sorry for taking so long to get back to you! This error is usually caused by the OpenCV DLL failing to load. Can you make sure the `cvextern.dll`, `concrt140.dll`, `msvcp140.dll`, and `vcruntime140.dll` files are in the folder where LoL Auto Login is running?
