### ISSUE TITLE
Fatal Error When Launching

### ISSUE THREAD

**Issue by Kyrluckechuck** [nicoco007/LoL-Auto-Login#25]
Hello again!

I am unsure if this is actually an issue or just something we need to live with, but I infrequently get this crash at launch (maybe 1 out of every 4 launches, but not consistently that many)

I can't tell you anything special about it, so I'm guessing it's some sort of race condition causing the wait to be skipped, or the application to fail to launch:
```
0:00:00:00.1755314 |  INFO | Waiting for 30000 ms
0:00:00:00.1835100 | FATAL | Could not start League of Legends!
```

What is odd is that usually the next launch works just fine...

[2019-04-24T15-00-01_LoLAutoLogin.log](https://github.com/nicoco007/LoL-Auto-Login/files/3113804/2019-04-24T15-00-01_LoLAutoLogin.log)

**Comment by nicoco007** [comment]
I could probably add some logic so it retries a few times before completely giving up on launching the client. I'll see what I can do.

I'll also have to add a message on why it wasn't able to launch because this message is _way_ too vague.

**Comment by nicoco007** [comment]
Turns out it's a really dumb race condition. Oops. Will be fixed in 2.1.1.

**Comment by nicoco007** [comment]
Feel free to reopen this issue if it happens again once the update is out!

**Comment by Kyrluckechuck** [comment]
Glad to hear it! Will do :)
