### ISSUE TITLE
New Patcher Removes This Executable (Corruption)

### ISSUE THREAD

**Issue by Kyrluckechuck** [nicoco007/LoL-Auto-Login#26]
During the corruption repair check (part of the new patcher), it auto removes this executable and data as part of the repair. 

Kinda hard to reproduce, so wondering if others can chime in if this affected them too? I manually reinstalled and it works as of now, but next patch it might get removed again.

Might be time to move outside of the League install folder?

Attached are the start logs from when it attempts to autologin after the patcher ran (it removed the /password file):
[2019-05-07T21-47-57_LoLAutoLogin.log](https://github.com/nicoco007/LoL-Auto-Login/files/3155114/2019-05-07T21-47-57_LoLAutoLogin.log)

**Comment by nicoco007** [comment]
I'll try to reproduce this at home tonight, but as you said it might be a good idea to move out of that folder either way. It might have to wait until 2.2.0 rather than 2.1.1 though; not sure yet.

Thanks for taking the time to write about these issues - it's very appreciated!

**Comment by Kyrluckechuck** [comment]
Can confirm that the update to 9.10 removed it the autologin executable automatically as part of the update process again, unfortunately!

**Comment by nicoco007** [comment]
I wasn't able to get the same behavior on my end even after a full repair but it's probably a better idea anyway to move the program to its own folder.

**Comment by Kyrluckechuck** [comment]
Very odd you're not able to reproduce it, but if you're going to move it anyways then I don't have an issue :P
