### ISSUE TITLE
Is this the end? (of external auto-login)

### ISSUE THREAD

**Issue by Kyrluckechuck** [nicoco007/LoL-Auto-Login#27]
Sorry that I know this isn't the proper forum for a question, but was just wondering if you're going to spend any more resources on this since after it is tested on the PBE Riot is going to add this functionality to the client natively (even so much as bypassing the login screen entirely)!

News Source:
https://na.leagueoflegends.com/en/news/client/client-features/saved-login-credentials-coming-soon

**Comment by nicoco007** [comment]
It only took them almost 10 years, haha. I guess the only reason to still use this program after that change is deployed everywhere would be to use the multi account feature I'm working on right now, but that's a pretty niche thing. Apart from that, yes, I guess it is the end.

**Comment by Kyrluckechuck** [comment]
So it looks like I was wrong about this being the end of any reason I saw for this -- any chance you want to integrate it with the PBE launcher, too, so that you could utilize this to switch between regular and PBE accounts? 😄
