### ISSUE TITLE
This program posted my password in a club chat 2 times, i cannot reproduce but this is awful!

### ISSUE THREAD

**Issue by thomasklemenc** [nicoco007/LoL-Auto-Login#28]

**Comment by Kyrluckechuck** [comment]
Can you provide any information or context to what happened (the steps roughly that you had performed)?

Whatever evidence you are sure this is LoL-Auto-Login related? (if you have any, it helps to speed this along and might help to reproduce, similar to above though)

Can you include the log files, too?

**Comment by nicoco007** [comment]
Closed due to inactivity.
