### ISSUE TITLE
Doesn't launcher login form

### ISSUE THREAD

**Issue by bartolije** [nicoco007/LoL-Auto-Login#3]
Hello,

I started the program, but it seems it doesn't "click" on Launch at the beginning

**Comment by nicoco007** [comment]
Hey! Sorry about this. What language is your launcher in? The program uses the color of the launch button to see if it can click on it, and it changes very slightly from one language to another, which is what may be causing your problem. Currently I have only tested the program with launchers in English and French, so if yours is in another language, I'll try adding compatibility for it ASAP.

**Comment by bartolije** [comment]
Hello,

English language on my side.
Seems it doesn't enter and valid pssword too

**Comment by nicoco007** [comment]
I think I have found the issue, because I have realized that I am also having a few issues once in a while. I think the "search" timeout is too short, so le program quits too early. I will push an update when I get the time (which should be either today or tomorrow).

**Comment by bartolije** [comment]
Hello,

Thank you very much for you answer.
Did you already consider using mouse movement on LoL windows instead of pixel search?
I just saw LoL window canno't be resized.

**Comment by nicoco007** [comment]
What do you mean by "mouse movement" ?

**Comment by bartolije** [comment]
I don't know if this is possible.
But since the LoL windows size canno't change, it should be possible to get the windows positions / size, them from a spedific point, move the mouse on the "Launch" button, and press login.

It would avoid pixel search, and support almost all language

**Comment by nicoco007** [comment]
The program doesn't look at every pixel on the screen; it just looks at a single pixel to see if it turns a certain shade of orange, indicating that the "Launch" button can be clicked. After that, il presses the button. I could probably change it so it looks for a range of colors instead of an exact color, but there is no real other way of finding out if the launch button is enabled or not.

**Comment by bartolije** [comment]
Oh, okay, I understand.
I thought you can process like that.
- Detect LoLPatcher Process
- Get LoLPatcher coordinate
- Mouve mouse to "Launch" button and click (since size of LoLPatcher is lmost always the same)
- Wait login windows. (or LoLPatcher  Exit event)
  If it doesn't disapear, then button isn't enable

Anyways, I'm just waiting to see the fix.
I was trying to learn with your code and try some things, but still get some errors / or don't detect LoL client :/

**Comment by nicoco007** [comment]
I've pushed an update. Everything should work now. If not, feel free to open another issue!
