### ISSUE TITLE
Doesn't find Launch button

### ISSUE THREAD

**Issue by bartolije** [nicoco007/LoL-Auto-Login#4]
Hello,

I tried with your latest update.
It doesn't find the button "Launch"

Maybe because of resolution / color screen?

Running in 1920*1080.
Here logs I got.

> 18/11/2015 17:49:38 [INFO] Started LoL Auto Login
> 18/11/2015 17:49:38 [INFO] Password file found!
> 18/11/2015 17:49:38 [WARN] League of Legends is already running!
> 18/11/2015 17:49:39 [INFO] Attempting to kill all League of Legends instances...
> 18/11/2015 17:49:40 [INFO] Waiting 30 seconds for League of Legends Patcher...
> 18/11/2015 17:49:41 [INFO] Found patcher after 1000 ms [Handle=1509528, Rectangle={Left=0,Top=0,Right=1280,Bottom=800}]
> 18/11/2015 17:49:41 [INFO] Waiting 30 seconds for Launch button to enable...

**Comment by nicoco007** [comment]
Could you add `--verbose` as a command-line argument, run it, and send me the new log?

**Comment by bartolije** [comment]
Hello,

Here it is.

> http://pastebin.com/ppHf6G29

**Comment by nicoco007** [comment]
Okay great! Could you also send me a screenshot of your launcher?

**Comment by bartolije** [comment]
Hello,

Here it is.

> http://i.imgur.com/x2XYcve.jpg

(maybe a different color, depending of graphic & screen configs? )

**Comment by nicoco007** [comment]
Could you try this version out? http://content.nicoco007.com/downloads/lol-auto-login/LoLAutoLogin-v1.1.4.zip

**Comment by bartolije** [comment]
Hello,

It work really better.
Juste got an issue on password input, but login still work.
Good job

**Comment by nicoco007** [comment]
Can you send me your latest log?

**Comment by nicoco007** [comment]
Does everything work now?

**Comment by bartolije** [comment]
Hello,

No, it detect the launch button, but on login, it click on password input, and do not enter password.
Maybe it could be great to have some delay to fix it?

> http://pastebin.com/5F4FFZZA

**Comment by nicoco007** [comment]
Could you try deleting the "password" file and re-entering your password into the program?

**Comment by bartolije** [comment]
Hello,

I already did that before launch and create tje log file

**Comment by nicoco007** [comment]
Oh okay. According to the log, it is detecting the password box, it's just not entering the password. Without moving your mouse, where does the cursor end up when the login form is shown? If it's not on the password box, that's probably the problem. I'm not sure what would be causing it, though.

**Comment by bartolije** [comment]
Hello,

Yeah, it detect the box, just doesn't enter the password.
I'm sorry to report / spam you like that with all these issue.

The mouse stop at this position.

> http://i.imgur.com/arOdEcr.png

**Comment by nicoco007** [comment]
No problem! I'm also trying to understand what is going on. What edition of Windows are you using?

**Comment by bartolije** [comment]
I'm using win7 64b.
If you need a teamviewer session, just tell me.

**Comment by nicoco007** [comment]
I've tried changing up the way your password is sent to the client. Could you try this version? http://content.nicoco007.com/downloads/lol-auto-login/LoLAutoLogin-v1.1.5.zip

I don't think a TeamViewer session would help since I wouldn't be able to get much more information out of it.

**Comment by nicoco007** [comment]
Since this issue seems to be dead, I'll close it. You can open a new one if you still have issues.
