### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by SanNick** [nicoco007/LoL-Auto-Login#5]
I start the programm and then starts LOL but the launcher the password was incorrect.
The correct password was saved in the password file can you please fix it.

**Comment by nicoco007** [comment]
Sorry for taking so long to answer! 

Do you have any special characters in your password (%, $, &, etc.) ? If so, could you tell me which one(s) ? (**don't give me your password**) Also, when you say "the correct password was saved in the password file", do you mean that the password file contains your password in normal text form? It is supposed to be stored in encrypted form.

**Comment by SanNick** [comment]
I have a . and a Ü in my password and it´s saved in normal text form. I mean that the password isn´t incorrect but then i start LoL the autologin try´s to use the password but it doesn´t work.

**Comment by nicoco007** [comment]
Okay, it's the normal text that's most likely the problem. Try deleting the `password` file, launch the program, enter your password in the program, and let it try to log you in again.

**Comment by SanNick** [comment]
I tried that. When the game starts i can see that the Auto-Login try´s to type in the password a few seconds but then comes wrong password.
It´s stored in encrypted form.

**Comment by nicoco007** [comment]
I've tried adding a Ü and a . to my password, and it does in fact fail. I'll try to see what the issue is and get back to you as soon as possible.

**Comment by SanNick** [comment]
Thank you, I hope that you can fix the issue.

**Comment by nicoco007** [comment]
[I've pushed an update](https://www.nicoco007.com/other-stuff/lol-auto-login/), it should work now. Could you try it out?

**Comment by SanNick** [comment]
Thank you it works :D
