### ISSUE TITLE
Doesn't log me in.

### ISSUE THREAD

**Issue by FAymYs19** [nicoco007/LoL-Auto-Login#7]
I saved my password and started the programm.
Then nothing happens any more.

P.S.
Before i the the little password box poped i get a few errors i simply skipped.

**Comment by nicoco007** [comment]
That's odd. Could you tell me what the error messages were? Are you running the normal client or the alpha client? If you're using the normal client, does it get you through the patcher (does it click on the "Launch" button for you)? What language/region are you running the game in?

**Comment by FAymYs19** [comment]
I reinstalled it into the LoL Folder. No more error's.
I'm playing on the normal client on EuW/english.
And it didn't even clicked the Launch button.
After i clicked the Launch button manually it didn't logged me in too.

**Comment by nicoco007** [comment]
Could you add `--verbose` as a command-line argument to the shortcut (right-click > Properties > Target, add `--verbose` after `"C:\Riot Games\League of Legends\LoLAutoLogin.exe"` or whatever it already says), start the program again, and then send me your latest log (which should be under `Logs\LoL Auto Login Logs` in your LoL folder) ? Also, what's your screen's resolution?

**Comment by nicoco007** [comment]
Since I have gotten no answer for a week now, I'll close the issue. If you still need help, please create a new issue.
