### ISSUE TITLE
Old Issue

### ISSUE THREAD

**Issue by FAymYs19** [nicoco007/LoL-Auto-Login#8]
Sry that i didnt answer you. ^^ 
(https://github.com/nicoco007/LoL-Auto-Login/issues/7#issuecomment-239687438)

I didn't looked my emails up latly.
I try to a the command line and it didn't helped.
It only open the LoL Client.
Doesn't click on Play niether enters the password to login. 
¯_(ツ)_/¯

**Comment by nicoco007** [comment]
Could you send me your most recent log file (it should be under `C:\Riot Games\League of Legends\Logs\LoL Auto Login Logs`, the one that has the closest time to now)

**Comment by nicoco007** [comment]
If you're going to start an issue, you need to reply. If I don't get an answer soon, I'll be forced to close this thread and block you from creating new issues, since these are currently going nowhere.
