### ISSUE TITLE
Program exits before League client can start up

### ISSUE THREAD

**Issue by lyjacky11** [nicoco007/LoL-Auto-Login#9]
As soon as the League patcher launches, the program exits/closes before it can click the Launch button.
I think the timing is too quick.

Please fix. Thanks!

**Comment by nicoco007** [comment]
Sorry for not answering earlier! Could you send me your most recent log file (it should be under C:\Riot Games\League of Legends\Logs\LoL Auto Login Logs or something similar)?

**Comment by lyjacky11** [comment]
Here is my recent logs with the errors described.

0:00:00:00.0035034 [INFO] Started LoL Auto Login v1.1.9.0
0:00:00:00.0390375 [INFO] Password file found!
0:00:00:00.0470452 [DEBUG] Attempting to start thread...
0:00:00:00.0995957 [INFO] Waiting 30000 ms for League of Legends Patcher...
0:00:00:00.1035995 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:00.1066024 [DEBUG] Failed to find window with specified arguments!
0:00:00:00.6100872 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:00.6135993 [DEBUG] Failed to find window with specified arguments!
0:00:00:01.1170731 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:01.1200762 [VERBOSE] Found window [Handle=2623052,Rectangle={Left=0,Top=0,Right=136,Bottom=39}]
0:00:00:01.1235799 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=0,Top=0,Right=1280,Bottom=800}]
0:00:00:01.1265825 [DEBUG] Correct window handle found!
0:00:00:01.1290857 [INFO] Found patcher after 1027.2074 ms {Handle=1377844, Rectangle={Left=0,Top=0,Right=1280,Bottom=800}}
0:00:00:01.1320878 [INFO] Waiting for Launch button to enable...
0:00:00:01.1481039 [VERBOSE] Color [A=255, R=0, G=0, B=0]
0:00:00:01.6525877 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:01.6555908 [VERBOSE] Found window [Handle=2623052,Rectangle={Left=0,Top=0,Right=136,Bottom=39}]
0:00:00:01.6590942 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=0,Top=0,Right=1280,Bottom=800}]
0:00:00:01.6625978 [DEBUG] Correct window handle found!
0:00:00:01.6791131 [VERBOSE] Color [A=255, R=0, G=0, B=0]
0:00:00:02.1830971 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:02.1856001 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:02.1876022 [DEBUG] Correct window handle found!
0:00:00:02.2011157 [VERBOSE] Color [A=255, R=0, G=41, B=47]
0:00:00:02.7055997 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:02.7076024 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:02.7096033 [DEBUG] Correct window handle found!
0:00:00:02.7231163 [VERBOSE] Color [A=255, R=0, G=41, B=47]
0:00:00:03.2276013 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:03.2316059 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:03.2356090 [DEBUG] Correct window handle found!
0:00:00:03.2511236 [VERBOSE] Color [A=255, R=201, G=129, B=37]
0:00:00:03.7556094 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:03.7576113 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:03.7611137 [DEBUG] Correct window handle found!
0:00:00:03.7746279 [VERBOSE] Color [A=255, R=202, G=129, B=37]
0:00:00:04.2786112 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:04.2811133 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:04.2831155 [DEBUG] Correct window handle found!
0:00:00:04.2941261 [VERBOSE] Color [A=255, R=202, G=129, B=37]
0:00:00:04.7981101 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:04.8006138 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:04.8026249 [DEBUG] Correct window handle found!
0:00:00:04.8221332 [VERBOSE] Color [A=255, R=202, G=129, B=37]
0:00:00:05.3266177 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:05.3291203 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:05.3311222 [DEBUG] Correct window handle found!
0:00:00:05.3426331 [VERBOSE] Color [A=255, R=202, G=129, B=37]
0:00:00:05.8466173 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:05.8496202 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:05.8521229 [DEBUG] Correct window handle found!
0:00:00:05.8641441 [VERBOSE] Color [A=255, R=202, G=129, B=37]
0:00:00:06.3681281 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:06.3716223 [VERBOSE] Found window [Handle=1377844,Rectangle={Left=320,Top=140,Right=1600,Bottom=940}]
0:00:00:06.3746252 [DEBUG] Correct window handle found!
0:00:00:06.3916513 [VERBOSE] Color [A=255, R=0, G=0, B=0]
0:00:00:06.9084998 [DEBUG] Trying to find window handle [ClassName=LoL Patcher,WindowName=LOLPATCHER,Size={Width=800, Height=600}]
0:00:00:06.9105109 [DEBUG] Failed to find window with specified arguments!

**Comment by nicoco007** [comment]
Could you tell me what your screen resolution is, and the region & language of your launcher?

**Comment by lyjacky11** [comment]
1920 x 1080
North America
English

**Comment by nicoco007** [comment]
That's odd, because I have the exact same setup. I'm quite busy right now, so it might take a while before I get back to you, but I'll try fixing it ASAP.

**Comment by lyjacky11** [comment]
Ya, no problem I'm not in a rush!
It worked before I reinstalled Windows 10 not sure what went wrong.

**Comment by nicoco007** [comment]
Okay, I think the problem is that the launcher changed its internal name and now LoL Auto Login isn't detecting it properly. I think it changes when you reinstall the launcher or something, so I'll try doing that and see what happens.

**Comment by nicoco007** [comment]
Would you mind trying to run an older version? I was told it was working on versions prior to 1.1.7. You can download older versions here: http://content.nicoco007.com/downloads/lol-auto-login/

**Comment by lyjacky11** [comment]
Sure thing! I'll report back if anything changes

**Comment by nicoco007** [comment]
Could you dowload [this file](https://github.com/nicoco007/LoL-Auto-Login/files/502126/lolaldiag-bundle.zip), extract it, run the lolaldiag.exe file, and send me the `.dump` file it creates? It's a diagnosis tool I made very quickly, so hopefully it works!

I forgot to write it down, but once you're logged in successfully, you need to click "Next" in the program.

**Comment by lyjacky11** [comment]
https://drive.google.com/file/d/0By-c61RYxgQVMzRjZy1UaEtqRm8/view?usp=sharing
Says the file is too big to upload here.

**Comment by nicoco007** [comment]
Could you try this out: [LoLAutoLogin-v2.0.0-rc.zip](https://github.com/nicoco007/LoL-Auto-Login/files/505324/LoLAutoLogin-v2.0.0-rc.zip)

Another quick question: when the program exits, does it exit on its own without you doing anything, or did you click on the launch button manually?

**Comment by lyjacky11** [comment]
it exits on its own, testing now.

**Comment by lyjacky11** [comment]
Thank you very much! It works perfectly fine! It clicks the launch and also enters password and logs on now! Thanks again and have a great day!
